{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.controller.enabled }}
{{- if gt .Values.controller.replicas 1.0 }}
  {{- fail "Key `controller.replicas` does not support values greater than 1." -}}
{{- end }}{{- /* if gt .Values.controller.replicas 1.0 */}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "slurm.controller.name" . }}
  namespace: {{ include "slurm.namespace" . }}
  labels:
    {{- include "slurm.controller.labels" . | nindent 4 }}
spec:
  podManagementPolicy: Parallel
  replicas: {{ .Values.controller.replicas | default 1 }}
  revisionHistoryLimit: 0
  serviceName: {{ include "slurm.controller.name" . }}
  selector:
    matchLabels:
      {{- include "slurm.controller.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: slurmctld
      labels:
        {{- include "slurm.controller.labels" . | nindent 8 }}
    spec:
      priorityClassName: {{ .Values.controller.priorityClassName | default .Values.priorityClassName }}
      automountServiceAccountToken: false
      {{- if .Values.controller.affinity }}
      affinity:
        {{- .Values.controller.affinity | toYaml | nindent 8 }}
      {{- end }}{{- /* if .Values.controller.affinity */}}
      {{- include "slurm.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.accounting.enabled }}
      securityContext:
        sysctls:
          - name: net.ipv4.ping_group_range
            value: "{{ include "slurm.uid" . }} {{ include "slurm.uid" . }}"
      {{- end }}{{- /* if .Values.accounting.enabled */}}
      initContainers:
        - name: init
          image: {{ include "slurm.controller.imageRef" . }}
          imagePullPolicy: {{ .Values.controller.imagePullPolicy | default (include "slurm.imagePullPolicy" .) }}
          env:
            - name: SLURM_USER
              value: {{ include "slurm.user" . }}
          command:
            - bash
            - -c
            - |
              {{- range .Files.Lines "scripts/init.sh" }}
              {{ . }}
              {{- end }}{{- /* range .Files.Lines "scripts/init.sh" */}}
          volumeMounts:
            {{- include "slurm.init.volumeMounts" . | nindent 12 }}
            - name: {{ include "slurm.controller.statesave.name" . }}
              mountPath: {{ include "slurm.controller.statesavePath" . }}
        {{- if .Values.accounting.enabled }}
        - name: wait
          image: {{ include "slurm.controller.imageRef" . }}
          securityContext:
            {{- include "slurm.securityContext" . | nindent 12 }}
          env:
            - name: HOST
              value: {{ include "slurm.accounting.name" . }}
          command:
            - bash
            - -c
            - |
              {{- range .Files.Lines "scripts/wait-ping.sh" }}
              {{ . }}
              {{- end }}{{- /* range .Files.Lines "scripts/wait-ping.sh" */}}
          volumeMounts:
            {{- include "slurm.init.volumeMounts" . | nindent 12 }}
        {{- end }}{{- /* if .Values.accounting.enabled */}}
      containers:
        - name: slurmctld
          image: {{ include "slurm.controller.imageRef" . }}
          imagePullPolicy: {{ .Values.controller.imagePullPolicy | default (include "slurm.imagePullPolicy" .) }}
          securityContext:
            {{- include "slurm.securityContext" . | nindent 12 }}
          {{- if .Values.controller.resources }}
          resources:
            {{- .Values.controller.resources | toYaml | nindent 12 }}
          {{- end }}{{- /* if .Values.controller.resources */}}
          ports:
            - name: slurmctld
              containerPort: {{ include "slurm.controller.port" . }}
          startupProbe:
            exec:
              command:
                - scontrol
                - ping
          readinessProbe:
            exec:
              command:
                - scontrol
                - ping
          volumeMounts:
            {{- include "slurm.volumeMounts" . | nindent 12 }}
            - name: authsocket
              mountPath: /run/slurmctld
            - name: {{ include "slurm.controller.statesave.name" . }}
              mountPath: {{ include "slurm.controller.statesavePath" . }}
        - name: reconfigure
          image: {{ include "slurm.controller.imageRef" . }}
          imagePullPolicy: {{ .Values.controller.imagePullPolicy | default (include "slurm.imagePullPolicy" .) }}
          env:
            - name: SLURM_USER
              value: {{ include "slurm.user" . }}
          command:
            - bash
            - -c
            - |
              {{- range .Files.Lines "scripts/reconfigure.sh" }}
              {{ . }}
              {{- end }}{{- /* range .Files.Lines "scripts/reconfigure.sh" */}}
          volumeMounts:
            {{- include "slurm.init.volumeMounts" . | nindent 12 }}
            - name: authsocket
              mountPath: /run/slurmctld
      volumes:
        {{- include "slurm.volumes" . | nindent 8 }}
        - name: slurm-config
          projected:
            defaultMode: 0600
            sources:
              - configMap:
                  name: {{ include "slurm.configMapName" . }}
              - secret:
                  name: {{ include "slurm.auth.secretName" . }}
              - secret:
                  name: {{ include "slurm.jwt.hs256.secretName" . }}
        {{- if .Values.controller.persistence.existingClaim }}
        - name: {{ include "slurm.controller.statesave.name" . }}
          persistentVolumeClaim:
            claimName: {{ tpl .Values.controller.persistence.existingClaim . }}
        {{- end }}{{- /* if .Values.controller.persistence.existingClaim */}}
  {{- if not .Values.controller.persistence.existingClaim }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "slurm.controller.statesave.name" . }}
        namespace: {{ include "slurm.namespace" . }}
        {{- if .Values.controller.persistence.annotations }}
        annotations:
          {{- toYaml .Values.controller.persistence.annotations | indent 10 }}
        {{- end }}{{- /* if .Values.controller.persistence.annotations */}}
        labels:
          {{- include "slurm.controller.labels" . | nindent 10 }}
          {{- if .Values.controller.persistence.labels }}
          {{- toYaml .Values.controller.persistence.labels | indent 10 }}
          {{- end }}{{- /* if .Values.controller.persistence.labels */}}
      spec:
        accessModes:
          {{- range .Values.controller.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.controller.persistence.size | quote }}
        storageClassName: {{ .Values.controller.persistence.storageClass | quote }}
        {{- if .Values.controller.persistence.selector }}
        selector:
          {{- toYaml .Values.controller.persistence.selector | indent 10 }}
        {{- end -}}{{- /* if .Values.controller.persistence.selector */}}
  {{- end -}}{{- /* if not .Values.controller.persistence.existingClaim */}}
{{- end }}{{- /* if .Values.controller.enabled */}}
