{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.login.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slurm.login.name" . }}
  namespace: {{ include "slurm.namespace" . }}
  labels:
    {{- include "slurm.login.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.login.replicas }}
  selector:
    matchLabels:
      {{- include "slurm.login.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "slurm.login.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.login.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      automountServiceAccountToken: false
      enableServiceLinks: false
      dnsConfig:
        {{- include "slurm.dnsConfig" . | nindent 8 }}
      {{- with .Values.login.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.login.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.login.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              {{- include "slurm.login.selectorLabels" . | nindent 12 }}
      {{- with .Values.login.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: login
        image: "{{ .Values.login.image.repository }}:{{ .Values.login.image.tag }}"
        imagePullPolicy: {{ .Values.login.imagePullPolicy | default .Values.imagePullPolicy }}
        {{- with .Values.login.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.login.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        - name: SLURM_CLUSTER_NAME
          value: {{ include "slurm.fullname" . }}
        - name: SLURM_CONF_SERVER  # TCL-4403: must use -controller service name
          value: {{ include "slurm.fullname" . }}-controller.{{ include "slurm.namespace" . }}.svc.cluster.local
        - name: SACKD_OPTIONS
          value: "--conf-server {{ include "slurm.fullname" . }}-controller.{{ include "slurm.namespace" . }}:6817"
        volumeMounts:
        - name: slurm-config
          mountPath: /etc/slurm
        {{- if .Values.login.sharedMemorySize }}
        - name: dshm
          mountPath: /dev/shm
        {{- end }}
        {{- if .Values.initScriptLogin }}
        - name: init-script
          mountPath: /root/init.sh
          subPath: init.sh
        {{- end }}
        {{- range .Values.login.extraVolumeMounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          {{- if .subPath }}
          subPath: {{ .subPath }}
          {{- end }}
          {{- if .readOnly }}
          readOnly: {{ .readOnly }}
          {{- end }}
        {{- end }}
      volumes:
      - name: slurm-config 
        projected:
          defaultMode: 0600
          sources:
          - secret:
              name: {{ include "slurm.fullname" . }}-auth-slurm
      {{- if .Values.login.sharedMemorySize }}
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: {{ .Values.login.sharedMemorySize }}
      {{- end }}
      {{- if .Values.initScriptLogin }}
      - name: init-script
        configMap:
          name: {{ include "slurm.initScriptLoginName" . }}
          defaultMode: 0755
      {{- end }}
      {{- range .Values.login.extraVolumes }}
      - name: {{ .name }}
        {{- if .configMap }}
        configMap:
          name: {{ .configMap.name }}
          {{- with .configMap.items }}
          items:
            {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- else if .secret }}
        secret:
          secretName: {{ .secret.secretName }}
          {{- with .secret.items }}
          items:
            {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- else if .persistentVolumeClaim }}
        persistentVolumeClaim:
          claimName: {{ .persistentVolumeClaim.claimName }}
        {{- else if .nfs }}
        nfs:
          server: {{ .nfs.server }}
          path: {{ .nfs.path }}
        {{- else if .emptyDir }}
        emptyDir: {}
        {{- else if .hostPath }}
        hostPath:
          path: {{ .hostPath.path }}
          {{- if .hostPath.type }}
          type: {{ .hostPath.type }}
          {{- end }}
        {{- end }}
      {{- end }}
{{- end }}